title: "Barathraj Manthiramoorthy"
url: "https://BarathRaj.github.io"
description: "Electrical Engineer | Robotics & AI Researcher"
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
